import { ArrowLeft, Download, Share2, FileText, Calendar, User } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useNavigate, useParams } from "react-router-dom";
import { useState, useEffect } from "react";
import { reportService } from "@/services/reportService";
import { useToast } from "@/hooks/use-toast";
import BottomNav from "@/components/BottomNav";

const ReportDetail = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const { toast: showToast } = useToast();
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (id) {
      fetchReport(id);
    }
  }, [id]);

  const fetchReport = async (reportId: string) => {
    try {
      const result = await reportService.getReport(reportId);
      if (result.success) {
        setReport(result.data);
      } else {
        showToast({
          title: "Error",
          description: "Failed to load report",
          variant: "destructive",
        });
        navigate('/health-records');
      }
    } catch (error) {
      console.error('Error fetching report:', error);
      showToast({
        title: "Error",
        description: "Failed to load report",
        variant: "destructive",
      });
      navigate('/health-records');
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    if (!report) return;

    const content = `
MEDICAL REPORT
${report.fileName}
Generated: ${new Date(report.uploadDate).toLocaleDateString()}
Patient: ${report.metadata?.patientName || 'N/A'}

REPORT TYPE: ${report.fileName}

SUMMARY:
${report.summary}

EXTRACTED TEXT:
${report.extractedText}

PARAMETERS:
${report.parameters.map((p: any) => `${p.name}: ${p.value} (${p.status})`).join('\n')}

---
This report was generated by AI-MED
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.fileName.replace(/\.[^/.]+$/, '')}_report.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    showToast({
      title: "Downloaded",
      description: "Report downloaded successfully",
    });
  };

  const handleShare = async () => {
    if (!report) return;

    const shareText = `Medical Report: ${report.fileName}\nDate: ${new Date(report.uploadDate).toLocaleDateString()}\n\nSummary: ${report.summary}`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Medical Report',
          text: shareText,
        });
      } catch (error) {
        console.log('Share cancelled');
      }
    } else {
      navigator.clipboard.writeText(shareText);
      showToast({
        title: "Copied",
        description: "Report summary copied to clipboard",
      });
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <p className="text-muted-foreground">Loading report...</p>
      </div>
    );
  }

  if (!report) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <p className="text-muted-foreground">Report not found</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background pb-24">
      {/* Header */}
      <div className="bg-gradient-to-b from-primary to-primary/90 text-primary-foreground px-6 pt-8 pb-6 rounded-b-[2rem]">
        <div className="flex items-center justify-between mb-4">
          <button
            onClick={() => navigate('/health-records')}
            className="w-12 h-12 bg-primary-foreground/20 rounded-full flex items-center justify-center"
          >
            <ArrowLeft className="w-6 h-6" />
          </button>
          <h1 className="text-2xl font-bold">Report Details</h1>
          <div className="w-12" />
        </div>
      </div>

      {/* Report Content */}
      <div className="px-6 mt-6 space-y-4">
        {/* Report Info Card */}
        <Card className="p-5 shadow-md">
          <div className="flex items-start justify-between mb-4">
            <div className="flex items-center gap-3">
              <div className="w-12 h-12 bg-primary/10 rounded-full flex items-center justify-center">
                <FileText className="w-6 h-6 text-primary" />
              </div>
              <div>
                <h2 className="font-bold text-lg">{report.fileName}</h2>
                <div className="flex items-center gap-4 text-sm text-muted-foreground mt-1">
                  <div className="flex items-center gap-1">
                    <Calendar className="w-3 h-3" />
                    <span>{new Date(report.uploadDate).toLocaleDateString()}</span>
                  </div>
                  {report.metadata?.patientName && (
                    <div className="flex items-center gap-1">
                      <User className="w-3 h-3" />
                      <span>{report.metadata.patientName}</span>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={handleDownload}
              className="flex-1"
            >
              <Download className="w-4 h-4 mr-2" />
              Download
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={handleShare}
              className="flex-1"
            >
              <Share2 className="w-4 h-4 mr-2" />
              Share
            </Button>
          </div>
        </Card>

        {/* AI Summary */}
        <Card className="p-5 shadow-md bg-sky-blue-light">
          <h3 className="font-bold mb-3 flex items-center gap-2">
            <span>🤖</span> AI Summary
          </h3>
          <p className="text-sm leading-relaxed">{report.summary}</p>
        </Card>

        {/* Parameters */}
        {report.parameters && report.parameters.length > 0 && (
          <Card className="p-5 shadow-md">
            <h3 className="font-bold mb-4">Parameters</h3>
            <div className="space-y-3">
              {report.parameters.map((param: any, idx: number) => (
                <div
                  key={idx}
                  className="flex items-center justify-between p-3 bg-secondary rounded-xl"
                >
                  <div className="flex-1">
                    <p className="font-medium">{param.name}</p>
                    <p className="text-sm text-muted-foreground">{param.value}</p>
                    {param.unit && (
                      <p className="text-xs text-muted-foreground mt-1">
                        Normal Range: {param.unit}
                      </p>
                    )}
                  </div>
                  <div
                    className={`w-3 h-3 rounded-full ${
                      param.status === "normal" ? "bg-green-500" :
                      param.status === "abnormal" ? "bg-yellow-500" : "bg-red-500"
                    }`}
                  />
                </div>
              ))}
            </div>
          </Card>
        )}

        {/* Extracted Text */}
        <Card className="p-5 shadow-md">
          <h3 className="font-bold mb-3">Extracted Text</h3>
          <div className="bg-secondary rounded-lg p-3 max-h-60 overflow-y-auto">
            <p className="text-sm text-muted-foreground whitespace-pre-line">
              {report.extractedText}
            </p>
          </div>
        </Card>
      </div>

      <BottomNav />
    </div>
  );
};

export default ReportDetail;
